### ISSUE TITLE
README Condescention

### ISSUE THREAD

**Issue by bschaeffer** [ebryn/ember-turbolinks#3]
The tone of this README seems to condescending when using the term `server generated applications`.  Thoughts?

**Comment by ebryn** [comment]
i don't see it, but maybe it's because i'm a condescending jerk? :disappointed:

**Comment by kristianfreeman** [comment]
FWIW I don't see it either ¯_(ツ)_/¯

**Comment by jamonholmgren** [comment]
I read it 2x, didn't see it. @bschaeffer, do you have a specific quote you take offense to?

**Comment by bschaeffer** [comment]
It was an attempt at a joke. Thought it would get lots of laughs.

![](http://www.quickmeme.com/img/d9/d9ed257881a6f54041454a5bffad221c29210456bad8630ba6f290e9baf72647.jpg)

**Comment by ebryn** [comment]
It was a day late! :P
